# Ref: https://www.mkdocs.org/getting-started/
# Ref: https://squidfunk.github.io/mkdocs-material/creating-your-site/
site_name: {{ site.name }}
site_url: https://blog.{{ site.url }}/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
plugins:
  - search
  - offline
nav:
  - Home: index.md
  - Architecture: architecture.md
